PrimerCrud/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PrimerCrud.Models;
using PrimerCrud.Filtros;

namespace PrimerCrud.Controllers
{
    public class AccessController : Controller
    {
        // GET: Access
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Usuario usuario)
        {
            ServicioBaseDeDatosUsuarios servicio = new ServicioBaseDeDatosUsuarios();
            List<Usuario> lista = servicio.ListaUsuarios();
            Usuario usuarioEnCuestion = lista.Where(x => x.User == usuario.User && x.Contraseña == usuario.Contraseña).FirstOrDefault();
            if (usuarioEnCuestion == null)
            {
                return Redirect("~/");
            }
            else
            {
                Session["User"] = usuarioEnCuestion;
                if(usuarioEnCuestion.IdTipoUsuario == 1)
                {
                    return RedirectToAction("MiPerfil", "MiPerfil");
                }
                else
                {
                    return Redirect("~/Usuarios/MostrarUsuarios");
                }
                
            }
        }

        public ActionResult Logout()
        {
            Session["User"] = null;
            return Redirect("~/Inicio");
        }
    }
}

PrimerCrud/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrimerCrud.Controllers
{
    public class InicioController : Controller
    {
        // GET: Inicio
        public ActionResult Inicio()
        {
            return View();
        }
    }
}

PrimerCrud/Views/Shared/_Layout.cshtml
@using PrimerCrud.Models
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="PEPE">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Inicio", "Inicio", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (Session["user"] != null)
                {
                <ul class="nav navbar-nav">
                    <li class="barra">@Html.ActionLink("Inicio", "Inicio", "Inicio")</li>
                    <li class="barra">@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li class="barra">@Html.ActionLink("Contacto", "Contact", "Home")</li>

                    @if (((Usuario)Session["user"]).IdTipoUsuario != 1)
                    {
                        <li class="barra">@Html.ActionLink("Ver Usuarios", "MostrarUsuarios", "Usuarios")</li>
                        <li class="barra">@Html.ActionLink("Lista de Personas", "Index", "Home")</li>
                    }
                    <li class="barra" style="margin-right:200px">@Html.ActionLink("Mi Perfil", "MiPerfil", "MiPerfil")</li>

                    <li class="barraa">@Html.ActionLink("Cerrar Sesion", "Logout", "Access")</li>

                </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/Global")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>


</html>